nova:
  instance:
      id: auto_increment(1)
      name: random_name(32)
      description: random_name(32)
      flavor_id: ref("flavor", "id")
      max_num: 1
      __meta__:
          count: 10
  flavor:
      id: auto_increment(100)
      name: random_name(32)
      type_id: ref("flavor_type", "id")
      property:
      __meta__:
          count: 2
  flavor_type:
      id: auto_increment(1000)
      name: random_name(32)
      property: "'text property'"
      __meta__:
          count: 2
